[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79f39fabc3e234dd0b5cc73ddde433116f5a9f22"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "3a0ceda1c2e094d20a0a32f4b0a817e50d956a9b9934a5ef6bc15b66f721015b"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b2d67d65c51e71565dc97423a64301cbc74c20f"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "e5a65dccfea1f4649ca46e2340910a5d4816eaa51d91f00c7a5635fcfb663e66"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da907342135b7e43979374e7ea34d1545a05be49"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "88b56c285180f6f5312889d29463ef5dfec2fdbb75677158ac66236cd3949eb3"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "166a88d9a784343071dc9a966d708c251da10675"
os = "windows"

    [[Tesseract.download]]
    sha256 = "cf16d9d086d98590cd742b53dd0a00e4a42b950157053b5d757ebbeb7e2e3e32"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34aa27548d4a46c4925f9edb7f94593fc8102c57"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "dfa08eae87c8f2756ba439fb01bdab82bde449181e3b992f3e189ac37e88a8b3"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.i686-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "263d5316ac2f04bb4a2ca076869c1c5d3f492892"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "931bd10e148f5919c886bd532a6effb5ccac8f5705a35c9867fe9723145e2938"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6122676e6fcf056c848fc44602582550e3c33b8"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "13d2f18a1175b11a49af05413e77efb6ae8ad19127dc3b7459a3f7031cbb22c9"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2115aff2841904c20e28a12cd19ec808d56884dc"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "1a37b2f58393a6857226629bf7a93dfd0dc2f5455cbb6017ad4b1cb8c035cd0a"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.i686-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a6b814a2916d86dadb6f2280ac00f29391a0cec"
os = "macos"

    [[Tesseract.download]]
    sha256 = "c79caed4434ca6522b4c3f76393947db90bd8e7a7f54b1a74a9276914725aefd"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2abaa2355182d3f18fa9556d762c98c747be770c"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "fdfa10923e239aeadff08f6a990089f775e6c46e53cafa6949c7297301bbb8db"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.i686-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49fcb3aa7bdc836faa1b5a571fb1d84cc1d6c71f"
os = "windows"

    [[Tesseract.download]]
    sha256 = "79860de8f8e4a37c90de11d6daec475ab411a38200dfcce8cb288798c079d867"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc2b52a50d19d0dcb34228dcebb6e9de20adae6f"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "462727952c9fd6e3c544e9862427bc147ef6981dbc2a7bd2a0dc1d58e4ccbe83"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cf658d47305a1268d79371249e7759eda342288"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "d88b247aa2496a4fbb390c1c89e7841e19c710fe2e7e851f7891b22a94ed1913"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddcb6b53a7fcdd12cd993e6d9388a88b317fb45d"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "2076f097832ce0e553904ec0b1b215f93570472a932d0445a5bfbfa64fa7f43d"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "775ac732e939b34d804a833676457cdf53fbc5ba"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "d03ca426fad8770c8a8a76fc0b7bc9a69cc4a74033e0338285325482ffefd762"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a20f4b3b14c4d1de0d39636ce3b544e5152dad0a"
os = "macos"

    [[Tesseract.download]]
    sha256 = "90a421fa5eada30ee87795851e84d609bafab175992d562675f39d91d430acaa"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4aeb114e159e1f73e02da705e22640db3f197448"
os = "freebsd"

    [[Tesseract.download]]
    sha256 = "90a79eef2150a7819f5cc543fc81ac2150bbbd121b5130eefd9ca4be1007ba71"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Tesseract]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a65bcf19a07e09b0123181a1f19838af83f31ec"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "745721736437c82a10c4a623e09dc3f169c34663c39147d5454150623794fb69"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edbd3aa484ba15788293f2aff5cd9be612d9667b"
os = "windows"

    [[Tesseract.download]]
    sha256 = "65fea98b5f64d4684d9e1216e781792f21620070df848d5c387f1b80e1d34cfc"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00c93bede101d867568c6a0f19cf7c3a45c4fa54"
os = "windows"

    [[Tesseract.download]]
    sha256 = "52086e030d9cfb87aee78bf85c70744aa0ebf3e6f0eea0be119f6dbe88c29a08"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af546a6ba4701d86cfdbcc8e10aec558578a6ca9"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "fc606fda6568b64a757e86f6096cd58d3dbf6ad04b311d05f39e957b00e64a95"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14f84128f2bd145935008534bb359d2246bc7760"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "088d9734149c298893c63e430a17ab4eee630f241f8334009c87c653462217c1"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41f58648dc5598abca1809c16dbc9c99bfc788ff"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "389865bfad1159eb9a7be83e5d4880897d0fd1b401551037bfe76c8fd180d606"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb4182c6bf6d2979852fce24cd6865308d8045bf"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "190f63e6246955d1b2c1a0c2fbb617d288cf41e74561c33019ca96fb2ce68ebf"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "164d7d500326485ff652d0aa7f54352052b18960"
os = "freebsd"

    [[Tesseract.download]]
    sha256 = "d85b82c83ce866701ce1700b476e5aff3b1853d03dca30adcef000adb92d902a"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b79e90dcc0dec8b2e555342256d2425507b24ae"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "13461dce55755b08142a813010b0abf2562d7f8663abf3256fe5e02dfc07dc8f"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v4.1.1+0/Tesseract.v4.1.1.i686-linux-musl-cxx03.tar.gz"
