[[Tesseract]]
arch = "aarch64"
git-tree-sha1 = "9cfd47bb6c65cc6745f6386f33699d75127ec447"
os = "macos"

    [[Tesseract.download]]
    sha256 = "0ef5ae8c18da03517e346bbab09c5a69ee9f4fb5f5593b2cf72a3e1923023f02"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.aarch64-apple-darwin.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eab6bcf031622d6cc9b811952134ae1b67dbd224"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "8a5651e3d16f35cf280e86bdc0f0a5d139f03b49010403670ce1f0e587682faa"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3249ae21044a8fa7caf2ec2773a6aceb7c87b27"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "73fc2a4a337a6e7a17c06080516592b91e0224449e4677f4ba86c07153977c91"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b79cdb1f41d2fe249ec9a4a700066d1e918b5db2"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "f657b51e0930cdec9b950c9377f262bf8a3c200aad0a9bd1575ee01de0d907db"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20f22e9c68b33e774581df20953eddd071812f72"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "59ff14c17fb7113e1322327ad14618ab205ce138bf2823b78e5eeba93a0bf6a6"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11e143f774389a9962d16f27df9ad010d0484ef6"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "80c038b2449ee56c392fbfb73a50692cf926541a67dce6d9b1d0b184a06f6ff0"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e77589c444bbdc0995696c012a0655065c62049c"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "50897ca0ef06ca6fb7d83c4c0137b7cfec78d67c59123b9b9db498dd387272e5"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37bdb59d316d5b8047efae136eb7180a7568edba"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "7dfbef7c58c810151fb6eb980abbbd6f028b4196e570309690a83d2d14cadec6"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5a58c165117f0086b53efa2fc9010341a58c932"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "794f777e9b6ba211578a24a3914cd1234dd48c618ff7d63e1f482adc7fe36c33"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "215d89eb4352a49566882d91c2a13f1e0b65fb94"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "99959732d48f37911534190bbbdaf033ca7a4c501a97526a03b8a3f950a4aba2"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff213dd997ae3040cb7af97d9e40a5f1c26db945"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "119dfc56d677da4291628deb9d062a95b93dea28729dfa53af72c0cb92519a3e"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "027f058d2b714e37f2b28d5d98674617687ef388"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "9b231cfa8bb4455f5e0d07aca386b38a20cff32361f05b5d959357dd8dd7d312"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b072130dda31077e8d3b16c2cc239c59e0d393f"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "6348b8ce392cebc52107cd1555db8a2ee65b0190bb597db7b844252377cdcada"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b252127d02005d365edbf98e6585d2bd041418f0"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "b2d73d820f816068b37fa53282b546e987f088b61568822b6d6a8eaa65db098f"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.i686-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "198fe48484d150de4687a6d4506b6c037b5124ca"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "6cc8b5e5c26cb72bb78e319464bdb67828789dc066f5eef5ad5ef63291573792"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2c42e6c22bbf5d12146ea43a317d7f6c8455575"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "0e5a4b7e54ddf76c9b7c62b696ac927a7252ecd2afe67925c1d01abd84122cca"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.i686-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee1b32a9992571647d71869e372271363a83b144"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "11cfcfc3ef5d493468c1897eaeb41a57c61f58be5e42501c90c29f3a29ed19b2"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.i686-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4384a295c81026e04e1d53bcc3573750cd6095b2"
os = "windows"

    [[Tesseract.download]]
    sha256 = "91b93c4c4ea818bc5e528b8488edada5ef8af0c25addddb89cc3d9a49c5e9e21"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28e253b297972cc5b899e3e24c919e27a40ee2ac"
os = "windows"

    [[Tesseract.download]]
    sha256 = "7872e6bcd6d7b6b2906a699d1323126f736c21cf0861bc3f8134d640f8c4cb31"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[Tesseract]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "564b42b8e4115d24acb3416150cd581fcbac4ec7"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "cba0fc900fdb307702e40dc62f2e5e67429f2086199e6f0a71d42efe2c89ccc9"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4310fee4e30085c51f1cc6be4192a7c641616f37"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "f24967db49b3c02ae2bb6854789584663f19003e2872dc5cbff6d95689008441"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
git-tree-sha1 = "d7be08957e5dcf22f93669c68bcabc5254517183"
os = "macos"

    [[Tesseract.download]]
    sha256 = "4bef5b77cf551b84a996747c75053222ff6d541c203421d9398710d998874f0c"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-apple-darwin.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b76c1064cc24bd6538f6bb8ea6b6826dd58846d"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "ccb9d335170b0a67e58c095031b038926087532c10a670694cfd528e3c14c73a"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a6050ae7030d92362298176533affc378cc84c6"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "2954a20d557573a00d6b4e14eee8747276f802caaf6b4eae8e0a7a7d8c2be318"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "327608e936dad7de6cd5e1e8f6229d6b036ebc9d"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "67c25731db927da91a27bc45256c7c6b3c7296411b4f8c5c199f68f3cb808426"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "411939bfb76267e70c1dc878d5abfcefaf9fdf4b"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "989745ff0c4b6a1afec46c4fc149c6545d53b182a9a286321d930b26576de02b"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
git-tree-sha1 = "7295b4468701253cc4aaf80d5363dbb0dd4836f7"
os = "freebsd"

    [[Tesseract.download]]
    sha256 = "6b9c4fadca566e4b09d58560f7d38e92b798e7a1da283cd27103ae20389fb88d"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-unknown-freebsd.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dcdb9aee54eab3a0702d6573e4f0a44e7a1d398"
os = "windows"

    [[Tesseract.download]]
    sha256 = "759b87ae87a3695309c70d42d969174726ba5658f0dbb1e0aeff9e8f04b28d7e"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad407313041a011de83fc2984fdce62cdeb9a184"
os = "windows"

    [[Tesseract.download]]
    sha256 = "69ec2c4f73edd92ecdf8532994055667e76d55629e8b5d46ddf3d5aa703cb074"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+1/Tesseract.v5.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
