[[Tesseract]]
arch = "aarch64"
git-tree-sha1 = "f40bef72a47f7e0725e87306155154b5c531e049"
os = "macos"

    [[Tesseract.download]]
    sha256 = "f10a4834e0eb2e70e2fe310e1daa77f366af32c0eb50a1fe409f9a4a3916d675"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.aarch64-apple-darwin.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "775f4967dcc5705cf8c6d2d1d0b7f660edd5fe48"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "708cd83435f85a5333121ab2a8534dd143278fbbc3f534865f8fdf8793d7d94e"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3806b3a0f99e1045bdfa40c1c0e95874bf75a41"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "59919ed53996bd3de9785ae8df0a6e45c0c1acc3e414f682197ff1177fee502a"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a98d5c3baedd11ded3557bf23862f6be80d7375"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "9afa51515cdcf4f685c7e99866927491e6a6ef8744de7eeb015dc1a5c6b568b8"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73d4672fcad0351e255f9434b6585ea56117d399"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "6360e428c07740976fdb919b40faf9696b3ad8cb8f9c456848f3e68166fc987d"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f9fe4b0262ca61577344acb600ba55ddc38b514"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "30aa44c547600878c2283c55954fe2908cbb1a7a3a6699461b98954e58b6d6c8"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "344a7e2fbfdb3e03cd42db990728dd9ad3f1d183"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "24ec2517984fa2a83d72b42f9f0373e7fb7b97a1de265bb3808014e492933bdc"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f06982036cd6f2bab1b0cefa94de7df6afa4626b"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "4960c3c4e3b51264e85f7eb5b49f54ce45c9ac28c33e9f2ac4be7fec554dc274"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "069f9f83909b2d0e8af469c447e4c061f1120d07"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "5b405d55511614cb2cd06f4d2f50fd5742b9c50a7495df8563722604b10fe637"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f9980b952bcddbc283ee73e7a8251fcf152a3b8"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "018bb76d6de15a2845c8ee5c605b6ef05d34acd630a8179ad180ae94d499dbce"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eb799e0e8cc3d88da93670b5ba849ebce98c4e9"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "3b3f8d4ca8d648126f5507e6e578f17d4cbdda9fbb27a429ddde9e211552ef48"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b608b6ccdfa121789970e921c4c013a748f9093"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "3721e9f45ac0cafc0c09b1b20c3f1b96474fe95062799572f5401364c9fd7b51"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Tesseract]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c33ad7486d5a5bc66fe9f04f6913c675723eb35e"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "cd5e7e5d12981b49cc79a93173109b5801d0d5898886596df65f8dc5d8ca19c4"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f2941f92298cc23b04f83b47d87c0986c51be1f"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "ee570750dea276b498888b238de8e491eb628d508ad0464af57fe3291f60cf66"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.i686-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd718b5f839a01828f576dbad83162f25c3bed86"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "7964390d9c85cf6ab73f5edb50cf87bcd52fbebbc3c46a52dc1a9c388afd18ad"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38685386f9947a499670d449d0687a47b7a8fa86"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "a809c0cb508972a4c69962e6eaf52da6a2dc0d5c3a325b617c5e1b738e0d2497"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.i686-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3951fc6b0076e4594b26a6547c46608a6f441dbe"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "902118de5b7b4d1bda61c8573c7f6d23ae08332ed07c8506430c7035dad21068"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.i686-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e385f98ab07bb312ade0afcd1cea8b5d7770d089"
os = "windows"

    [[Tesseract.download]]
    sha256 = "3cd60b8e3b305b517591665708cb27e352dae43d5180eac74202b666b3d6f5a4"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[Tesseract]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1864b999bff6f52323889bb03fa2b46473a6692"
os = "windows"

    [[Tesseract.download]]
    sha256 = "34ab77c5c4bbe8ad52973ab994bca0346f662892d58d08cf07777ca61c757d52"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[Tesseract]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22ae062df535cde21eaea1033e1dc8a35358a41e"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "a25fadcefb41afe573514f021713ba168eaacf306c31afd76cf837eaed6f5c55"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc71d7804b87b9cda9e97370ad8ddc671b71fdf2"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "55b73d12222d46bb4df601b1d7274f2c9f6848affffca2c47a56f03b5259c9f8"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
git-tree-sha1 = "fd925c8083aa8aa0fefa58de62736931a7a6430c"
os = "macos"

    [[Tesseract.download]]
    sha256 = "c2ab0b7c7a3c2e8be3d6172829442dc2a8c37bfee3247e8446069f5005d58988"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-apple-darwin.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6a072a11dc266fbc55051787fa2228ecf76b2f2"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "f7f6004dc611bcc93115338962429c9faa55efde52e44818e46ae7e6bec8beef"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6188b8ed0aac33e709faade346b52a0798237610"
libc = "glibc"
os = "linux"

    [[Tesseract.download]]
    sha256 = "0369a2dfe5cbd482e09488168249aa23d3ee7bb882943200db134d6e87326d72"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5954416ea906fe14f32d12773ad389efeec1b48a"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "e496d1d86e766875f666f74bc11f337b926e3e0a13efd35c050dab580ac5a7d7"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "346013c9f50acc4894b8fa80e9976fa6601762e5"
libc = "musl"
os = "linux"

    [[Tesseract.download]]
    sha256 = "6a259b31783d5d25164a0b97f90454af82a80118a3ca5759c01b86f54e96a03c"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[Tesseract]]
arch = "x86_64"
git-tree-sha1 = "b165f2a26d319e6e85838bfbfd18ec755e402ea8"
os = "freebsd"

    [[Tesseract.download]]
    sha256 = "7be56777c37c22ef48dc4bbe78c68c9776526c57ef500632c14f988e8bd46150"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-unknown-freebsd.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c87a6bb963896962958a4c47b82e7508b2f6399f"
os = "windows"

    [[Tesseract.download]]
    sha256 = "1eb0d826a827e17d6ea9e39cdd46eb344a4729f69cae8645da886b6c908f4546"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Tesseract]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "357ef8e154e20f4086ca000f6bd395440b15d651"
os = "windows"

    [[Tesseract.download]]
    sha256 = "59b843a353960550db480cf92c90f829b269d147a39ffa8ba0a0bac02f66b7bd"
    url = "https://github.com/JuliaBinaryWrappers/Tesseract_jll.jl/releases/download/Tesseract-v5.1.0+0/Tesseract.v5.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
